// Mocks generated by Mockito 5.4.2 from annotations
// in crypto_currency/test/feature/home/data/data_source/remote/home_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:crypto_currency/core/network/dio.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DioCore].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioCore extends _i1.Mock implements _i3.DioCore {
  MockDioCore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, String> get header => (super.noSuchMethod(
        Invocation.getter(#header),
        returnValue: <String, String>{},
      ) as Map<String, String>);
  @override
  set header(Map<String, String>? _header) => super.noSuchMethod(
        Invocation.setter(
          #header,
          _header,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, String> get headerWithToken => (super.noSuchMethod(
        Invocation.getter(#headerWithToken),
        returnValue: <String, String>{},
      ) as Map<String, String>);
  @override
  set headerWithToken(Map<String, String>? _headerWithToken) =>
      super.noSuchMethod(
        Invocation.setter(
          #headerWithToken,
          _headerWithToken,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i2.Response<dynamic>> get({
    required String? path,
    dynamic queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #get,
            [],
            {
              #path: path,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> post({
    required String? path,
    Object? data,
    dynamic queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [],
          {
            #path: path,
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #post,
            [],
            {
              #path: path,
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> patch({
    required String? path,
    dynamic queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #patch,
            [],
            {
              #path: path,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> put({
    required String? path,
    dynamic queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #put,
            [],
            {
              #path: path,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> delete({
    required String? path,
    dynamic queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
            #headers: headers,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #delete,
            [],
            {
              #path: path,
              #queryParameters: queryParameters,
              #headers: headers,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}
